### ISSUE TITLE
Error with fresh install

### ISSUE THREAD

**Issue by DatenThielt** [dshook/UnitySaveEditor#4]
I added this to my unity project, however my first issue is that I had to change Colors to Color on line 113 as Colors was not valid,  And even after fixing that I am unable to load any saves,  When it try's to access any directory it gets permissions denied (Even after changing the permissions on said directory to anyone)

I am using unity version 2020.1.0b7.3556 Personal and the latest version of this plugin.
![image](https://user-images.githubusercontent.com/4466326/87229366-71705a80-c375-11ea-88d0-a6234d6c5d0b.png)

Thanks!

**Comment by dshook** [comment]
Sorry for the big delay in responding, I didn't see any notification for this hah.  I did just push up the fix for the `Colors` problem (was a little cruft from separating it from my project) so thanks for catching that.

As for the permission problem, I don't think I can help much there other than to suggest looking at the permissions on that folder.  The code is just doing a normal folder open and it's getting a permission denied from windows there.

**Comment by DatenThielt** [comment]
No Worries, Unfortunately this was some time ago and we have sinced ceased the project , But thank you for looking into it and fixing said issue with colors!
